/**
 * @mindvault/registry-client
 *
 * Thin, typed wrapper around the auto-generated Soroban TypeScript bindings
 * for the `vault-registry` contract. Bindings are regenerated by running
 * `pnpm contract:bindings` at the repo root.
 *
 * Consumers (server/, web/, mcp/) import from this package rather than the
 * `generated/` folder directly so we have one place to:
 *   - swap RPC URLs / network passphrases
 *   - add ergonomic helpers (e.g. unit conversion)
 *   - re-export the generated types under stable names
 */

import { Networks } from "@stellar/stellar-sdk";

// Re-export everything the bindings generator produced. The Client class,
// the Resource type, error variants, and network defaults all flow through.
export * from "./generated/index.js";

import { Client, type Resource } from "./generated/index.js";

/** Options for creating a {@link VaultRegistryClient}. */
export interface RegistryClientOptions {
  /** The deployed vault-registry contract ID (C…). */
  contractId: string;
  /** Soroban RPC URL (e.g. https://soroban-testnet.stellar.org). */
  rpcUrl: string;
  /**
   * Network passphrase. Defaults to {@link Networks.TESTNET}. Pass
   * {@link Networks.PUBLIC} for mainnet.
   */
  networkPassphrase?: string;
  /**
   * Optional public key for read-only calls. Write calls require a signer
   * supplied separately by the caller (see the generated Client docs).
   */
  publicKey?: string;
}

/**
 * Construct a {@link Client} configured against the given Soroban RPC and
 * deployed contract. This is the only entry point most callers need.
 */
export function createRegistryClient(opts: RegistryClientOptions): Client {
  return new Client({
    contractId: opts.contractId,
    rpcUrl: opts.rpcUrl,
    networkPassphrase: opts.networkPassphrase ?? Networks.TESTNET,
    publicKey: opts.publicKey,
  });
}

/** Convenience alias so callers can write `VaultRegistryClient` if preferred. */
export type VaultRegistryClient = Client;

export async function listResources(
  client: Client,
  start: number,
  limit: number,
): Promise<Resource[]> {
  const tx = await (client as any).list({ start, limit });
  return tx.result as Resource[];
}
